apiVersion: v1
kind: Namespace
metadata:
  name: heptio-contour
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour
  namespace: heptio-contour
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routes.contour.heptio.com
  labels:
    component: route
spec:
  group: contour.heptio.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: routes
    kind: Route