apiVersion: v1
kind: Service
metadata:
 name: redis
 namespace: heptio-contour
spec:
 ports:
 - port: 6379
   protocol: TCP
 selector:
   app: redis
 type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: heptio-contour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: contour
        image: redis:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
      serviceAccountName: contour

